Repository NibiruChain/py-sdk, pull requests merged in 2022-08, with the labels that each got.

#38 ci,tests: Verify the SDK works with tests and set up GHA workflow to build and run from scratch
  .github/workflows/pytests.yml
  Pipfile
  Pipfile.lock
  README.md
  tests/__init__.py
  tests/chain_info_test.py
Labels: enhancement

#49 refactor: fix protogen script
  scripts/protocgen.sh
Labels: bug, enhancement

#55 docs(README): Documented entire development setup. Fixed badges. Added installation instructions for pyenv, poetry, pip
  .github/workflows/pytests.yml
  .python-version
  LICENSE
  README.md
Labels: documentation

#60 update CHANGELOG for v0.0.14a1
  CHANGELOG.md
  README.md
Labels: docs

#103 hotfix/test(query_clients): Test vpool.query.all_pools fn. Account for deserialize edge case #102.
  nibiru/query_clients/util.py
  nibiru/sdk.py
  nibiru/utils.py
  tests/__init__.py
  tests/chain_info_test.py
  tests/perp_test.py
  tests/vpool_test.py
Labels: tests

#109 chore(release): Update nibiru-proto dependency for v0.14.0 binary
  CHANGELOG.md
  nibiru/query_clients/vpool.py
  poetry.lock
  pyproject.toml
  tests/pricefeed_test.py
  tests/vpool_test.py
Labels: tests

#111 cast str to float safely | v0.3
  nibiru/query_clients/vpool.py
  pyproject.toml
  tests/vpool_test.py
Labels: enhancement

#112 chore: releases/v0.3.0
  CHANGELOG.md
Labels: docs
